# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efeaaecbf009cd9f9a65a0319074a0b0011e6a27f4e80907f8559a42690dd368f6fec16b3661594a7cdb348574128f683bfc6333b955cc4d713e7a0a227e3029

test:
  secret_key_base: 8a278e2800149fadf51ffc0caf73e1748f276ab07ece2b649e50e438fc8f8b3cc66e2078b539c27ca7b2ba2f91cfea413b75baca05a949852dd57690f36e4881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
